# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Write the synthetic fixture the example golden and the example
helper read, so it is reproducible from this file alone (the
fixture-provenance rule: every fixture's source is recorded, and a
synthetic one is generated by a committed script, never by hand).

The series is closed-form, not drawn from a random generator, so the
same bytes come out on every machine and every Python: 48 monthly
values from 2020-01 to 2023-12 of a quantity near 1.0 with a small
annual cycle and a slower modulation, rounded to four decimals.

  uv run verification/fixtures/make_fixtures.py [--out example_series.csv]

A fixture builder lives here, beside the fixture it writes, and is not
a golden: the goldens workflow runs the notebooks at the top of
verification/ and nothing under fixtures/. No skill invokes it (the
placement rule, ADR C).
"""

import argparse
import csv
import math
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_OUT = HERE / "example_series.csv"


def series(months: int = 48) -> list[tuple[str, float]]:
    rows = []
    for i in range(months):
        year, month = 2020 + i // 12, 1 + i % 12
        value = 1.0 + 0.08 * math.sin(2 * math.pi * i / 12) + 0.02 * math.cos(2 * math.pi * i / 5)
        rows.append((f"{year:04d}-{month:02d}", round(value, 4)))
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    with args.out.open("w", newline="") as fh:
        writer = csv.writer(fh, lineterminator="\n")
        writer.writerow(["month", "value"])
        writer.writerows(series())
    print(f"wrote {args.out} ({len(series())} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
